import type { BuildResult, CutLayer, CutPath, Point } from '../geometry/types'

export const LAYER_STYLE: Record<CutLayer, { stroke: string; label: string }> = {
  cut: { stroke: '#0066ff', label: 'Cut' },
  bend: { stroke: '#ff6a00', label: 'Bend lines (reference — do not cut)' },
}

function fmt(n: number): string {
  return (Math.round(n * 1000) / 1000).toString()
}

/** Shifts a part so its bounding box starts at (0, 0) — CAM software and
 * the cutting table both expect positive coordinates. */
export function normalizedPaths(result: BuildResult): CutPath[] {
  const { minX, minY } = result.bounds
  return result.paths.map((p) => ({ ...p, points: p.points.map((q): Point => ({ x: q.x - minX, y: q.y - minY })) }))
}

export function pathToSvgD(points: Point[], closed: boolean, height: number): string {
  if (points.length === 0) return ''
  const parts = points.map((p, i) => `${i === 0 ? 'M' : 'L'}${fmt(p.x)} ${fmt(height - p.y)}`)
  return parts.join(' ') + (closed ? ' Z' : '')
}

export function serializeSvg(result: BuildResult, opts: { includeBend: boolean; name: string }): string {
  const w = result.stats.widthMm
  const h = result.stats.heightMm
  const paths = normalizedPaths(result)
  const layers: CutLayer[] = opts.includeBend ? ['cut', 'bend'] : ['cut']
  const groups = layers
    .map((layer) => {
      const d = paths
        .filter((p) => p.layer === layer)
        .map((p) => `    <path d="${pathToSvgD(p.points, p.closed, h)}"/>`)
        .join('\n')
      return `  <g id="${layer}" inkscape:label="${LAYER_STYLE[layer].label}" inkscape:groupmode="layer" fill="none" stroke="${LAYER_STYLE[layer].stroke}" stroke-width="0.1">\n${d}\n  </g>`
    })
    .join('\n')
  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${opts.name} — generated by Holtzman. Units: mm. Paths are kerf-centrelines. -->
<svg xmlns="http://www.w3.org/2000/svg" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" width="${fmt(w)}mm" height="${fmt(h)}mm" viewBox="0 0 ${fmt(w)} ${fmt(h)}">
${groups}
</svg>
`
}
